AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodePipeline for the report-trigger lambda'

Parameters:
  RepositoryName:
    Type: String
    Default: report-trigger
  MainVpcId:
    Type: String
    Default: 'vpc-92705df7'
  MobileInsightNatSubnetId:
    Type: String
    Default: 'subnet-1091084d'
  AllVpcTrafficSecurityGroupId:
    Type: String
    Default: 'sg-cc1adbab'

Resources:
  CodeCommitEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources:
          - !Join 
            - ''
            - - 'arn:aws:codecommit:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - !Ref RepositoryName
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - master
      Targets:
        - Arn: !Join 
            - ''
            - - 'arn:aws:codepipeline:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - !Ref AppPipeline
          RoleArn: !ImportValue CodePipelineEventRoleArn
          Id: codepipeline-AppPipeline

  AppBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Ref RepositoryName
      ServiceRole: !ImportValue CodeBuildGenericServiceRoleArn
      Source:
        Type: 'CODEPIPELINE'
      Artifacts:
        Type: 'CODEPIPELINE'
      Environment:
        ComputeType: 'BUILD_GENERAL1_SMALL'
        Type: 'LINUX_CONTAINER'
        Image: 'aws/codebuild/python:3.7.1'
        EnvironmentVariables:
          - Name: 'LAMBDA_ARTIFACTS_BUCKET'
            Value: !ImportValue CodeBuildArtifactStoreBucketName
          - Name: 'LAMBDA_CODE_KEY'
            Value: !Join
              - ''
              - - !Ref RepositoryName
                - '/'
                - 'lambda-code'
      VpcConfig:
        VpcId: !Ref MainVpcId
        Subnets:
          - !Ref MobileInsightNatSubnetId
        SecurityGroupIds:
          - !Ref AllVpcTrafficSecurityGroupId

  AppPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Ref RepositoryName
      RoleArn: !ImportValue CodePipelineServiceRoleArn
      ArtifactStore:
        Type: S3
        Location: !ImportValue CodePipelineArtifactStoreBucketName
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                BranchName: master
                RepositoryName: !Ref RepositoryName
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref AppBuild
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              InputArtifacts:
                - Name: BuildOutput
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                StackName: !Join
                  - ''
                  - - !Ref RepositoryName
                    - '-lambda'
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                TemplatePath: BuildOutput::output-template.yml
                RoleArn: !ImportValue CloudFormationServiceRoleArn
              RunOrder: 1
